/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef UNREALED_API
#define UNREALED_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern UNREALED_API FName UNREALED_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class UNREALED_API UUnrealEdEngine : public UEditorEngine
{
public:
    INT NotifyVtbl;
    INT hWndMain;
    DECLARE_CLASS(UUnrealEdEngine,UEditorEngine,0|CLASS_Transient|CLASS_Config,UnrealEd)
    NO_DEFAULT_CONSTRUCTOR(UUnrealEdEngine)
};


class UNREALED_API AAnimBrowserMesh : public AActor
{
public:
    DECLARE_CLASS(AAnimBrowserMesh,AActor,0,UnrealEd)
    NO_DEFAULT_CONSTRUCTOR(AAnimBrowserMesh)
};


class UNREALED_API UAnimEditProps : public UObject
{
public:
    INT WBrowserAnimationPtr;
    FLOAT GlobalCompression;
    DECLARE_CLASS(UAnimEditProps,UObject,0,UnrealEd)
    NO_DEFAULT_CONSTRUCTOR(UAnimEditProps)
};


class UNREALED_API UMeshEditProps : public UObject
{
public:
    INT WBrowserAnimationPtr;
    INT LODStyle;
    FLOAT VisSphereRadius;
    FLOAT LOD_Strength;
    class UMeshAnimation* DefaultAnimation;
    TArrayNoInit<class UMaterial*> Material;
    TArrayNoInit<FLODLevel> LODLevels;
    FVector Scale;
    FVector Translation;
    FRotator Rotation;
    FVector MinVisBound;
    FVector MaxVisBound;
    FVector VisSphereCenter;
    DECLARE_CLASS(UMeshEditProps,UObject,0,UnrealEd)
    NO_DEFAULT_CONSTRUCTOR(UMeshEditProps)
};


class UNREALED_API UNotifyProperties : public UObject
{
public:
    INT OldArrayCount;
    INT WBrowserAnimationPtr;
    TArrayNoInit<FNotifyInfo> Notifys;
    DECLARE_CLASS(UNotifyProperties,UObject,0,UnrealEd)
    NO_DEFAULT_CONSTRUCTOR(UNotifyProperties)
};


class UNREALED_API USequEditProps : public UObject
{
public:
    INT WBrowserAnimationPtr;
    FLOAT Rate;
    FLOAT Compression;
    FName SequenceName;
    TArrayNoInit<FName> Groups;
    DECLARE_CLASS(USequEditProps,UObject,0,UnrealEd)
    NO_DEFAULT_CONSTRUCTOR(USequEditProps)
};


class UNREALED_API USkelPrefsEditProps : public UObject
{
public:
    INT WBrowserAnimationPtr;
    INT LODStyle;
    INT RootZero;
    DECLARE_CLASS(USkelPrefsEditProps,UObject,0,UnrealEd)
    NO_DEFAULT_CONSTRUCTOR(USkelPrefsEditProps)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
