@echo off
del core.u
del engine.u
del fire.u
del editor.u
del uwindow.u
del ipdrv.u
del gameplay.u
del r6sfx.u
del r6abstract.u
del r6engine.u
del r6Characters.u
del r61stweapons.u
del r6Weapons.u
del r6WeaponGadgets.u
del r63rdweapons.u
del r6description.u
del r6gameservice.u
del r6game.u
del r6window.u
del r6menu.u
del unrealed.u
ucc make
