/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef CORE_API
#define CORE_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern CORE_API FName CORE_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(Main)

#ifndef NAMES_ONLY


class CORE_API USubsystem : public UObject
{
public:
    INT ExecVtbl;
    DECLARE_CLASS(USubsystem,UObject,0,Core)
    NO_DEFAULT_CONSTRUCTOR(USubsystem)
};


struct UCommandlet_eventMain_Parms
{
    FString Parms;
    INT ReturnValue;
};
class CORE_API UCommandlet : public UObject
{
public:
    BITFIELD LogToStdout:1 GCC_PACK(4);
    BITFIELD IsServer:1;
    BITFIELD IsClient:1;
    BITFIELD IsEditor:1;
    BITFIELD LazyLoad:1;
    BITFIELD ShowErrorCount:1;
    BITFIELD ShowBanner:1;
    FStringNoInit HelpCmd GCC_PACK(4);
    FStringNoInit HelpOneLiner;
    FStringNoInit HelpUsage;
    FStringNoInit HelpWebLink;
    FStringNoInit HelpParm[16];
    FStringNoInit HelpDesc[16];
    DECLARE_FUNCTION(execMain);
    INT eventMain(const FString& Parms)
    {
        UCommandlet_eventMain_Parms Parms;
        Parms.ReturnValue=0;
        Parms.Parms=Parms;
        ProcessEvent(FindFunctionChecked(CORE_Main),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UCommandlet,UObject,0|CLASS_Transient,Core)
    NO_DEFAULT_CONSTRUCTOR(UCommandlet)
};

#endif

AUTOGENERATE_FUNCTION(UCommandlet,-1,execMain);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
