/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef R6WEAPONS_API
#define R6WEAPONS_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern R6WEAPONS_API FName R6WEAPONS_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(HideAttachment)
AUTOGENERATE_NAME(NbBulletChange)
AUTOGENERATE_NAME(SetGadgetStaticMesh)

#ifndef NAMES_ONLY

#define UCONST_AccuracyLostWhenWounded 1.2

struct AR6Weapons_eventHideAttachment_Parms
{
};
class R6WEAPONS_API AR6Weapons : public AR6AbstractWeapon
{
public:
    BYTE m_aiNbOfBullets[20];
    BYTE m_iNbOfRoundsInBurst;
    BYTE m_eRateOfFire;
    BYTE m_wNbOfBounce;
    INT C_iMaxNbOfClips;
    INT m_iClipCapacity;
    INT m_iNbOfClips;
    INT m_iNbOfExtraClips;
    INT m_iCurrentClip;
    INT m_iNbOfRoundsToShoot;
    INT m_iCurrentNbOfClips;
    INT m_iCurrentAverage;
    INT m_iDbgNextReticule;
    BITFIELD m_bPlayLoopingSound:1 GCC_PACK(4);
    BITFIELD m_bSoundLog:1;
    BITFIELD bShowLog:1;
    BITFIELD m_bFireOn:1;
    BITFIELD m_bEmptyAllClips:1;
    FLOAT m_fMuzzleVelocity GCC_PACK(4);
    FLOAT m_MuzzleScale;
    FLOAT m_fAverageDegChanges;
    FLOAT m_fAverageDegTable[5];
    FLOAT m_fStablePercentage;
    FLOAT m_fWorstAccuracy;
    FLOAT m_fOldWorstAccuracy;
    FLOAT m_fEffectiveAccuracy;
    FLOAT m_fDesiredAccuracy;
    FLOAT m_fMaxAngleError;
    FLOAT m_fCurrentFireJump;
    FLOAT m_fFireSoundRadius;
    FLOAT m_fRateOfFire;
    FLOAT m_fDisplayFOV;
    class UTexture* m_WeaponIcon;
    class AR6Reticule* m_ReticuleInstance;
    class AR6SFX* m_pEmptyShellsEmitter;
    class AR6SFX* m_pMuzzleFlashEmitter;
    class UClass* m_pReticuleClass;
    class UClass* m_pWithWeaponReticuleClass;
    class UClass* m_pBulletClass;
    class UClass* m_pEmptyShells;
    class UClass* m_pMuzzleFlash;
    FstWeaponCaps m_stWeaponCaps;
    FRotator m_rLastRotation;
    FRotator m_rBuckFirstBullet;
    FstAccuracyType m_stAccuracyValues;
    FVector m_vPawnLocWhenKilled;
    void eventHideAttachment()
    {
        ProcessEvent(FindFunctionChecked(R6WEAPONS_HideAttachment),NULL);
    }
    DECLARE_CLASS(AR6Weapons,AR6AbstractWeapon,0,R6Weapons)
    NO_DEFAULT_CONSTRUCTOR(AR6Weapons)
};


class R6WEAPONS_API AR6Gadget : public AR6Weapons
{
public:
    DECLARE_CLASS(AR6Gadget,AR6Weapons,0,R6Weapons)
    NO_DEFAULT_CONSTRUCTOR(AR6Gadget)
};


struct AR6DemolitionsGadget_eventSetGadgetStaticMesh_Parms
{
};
struct AR6DemolitionsGadget_eventNbBulletChange_Parms
{
};
class R6WEAPONS_API AR6DemolitionsGadget : public AR6Gadget
{
public:
    BITFIELD m_bDetonated:1 GCC_PACK(4);
    BITFIELD m_bChargeInPosition:1;
    BITFIELD m_bCanPlaceCharge:1;
    BITFIELD m_bInstallingCharge:1;
    BITFIELD m_bCancelChargeInstallation:1;
    BITFIELD m_bRaiseWeapon:1;
    BITFIELD m_bHide:1;
    BITFIELD m_bDetonator:1;
    class AR6Reticule* m_ReticuleConfirm GCC_PACK(4);
    class AR6Reticule* m_ReticuleBlock;
    class AR6Reticule* m_ReticuleDetonator;
    class UStaticMesh* m_DetonatorStaticMesh;
    class UTexture* m_DetonatorTexture;
    class UStaticMesh* m_ChargeStaticMesh;
    class AR6Grenade* BulletActor;
    FName m_ChargeAttachPoint;
    FName m_DetonatorAttachPoint;
    class UClass* m_pExplosionParticles;
    class UClass* m_pReticuleBlockClass;
    class UClass* m_pDetonatorReticuleClass;
    FVector m_vLocation;
    void eventSetGadgetStaticMesh()
    {
        ProcessEvent(FindFunctionChecked(R6WEAPONS_SetGadgetStaticMesh),NULL);
    }
    void eventNbBulletChange()
    {
        ProcessEvent(FindFunctionChecked(R6WEAPONS_NbBulletChange),NULL);
    }
    DECLARE_CLASS(AR6DemolitionsGadget,AR6Gadget,0,R6Weapons)
    NO_DEFAULT_CONSTRUCTOR(AR6DemolitionsGadget)
};

enum eGrenadeThrow
{
    GRENADE_None            =0,
    GRENADE_Throw           =1,
    GRENADE_Roll            =2,
    GRENADE_RemovePin       =3,
    GRENADE_PeekLeft        =4,
    GRENADE_PeekRight       =5,
    GRENADE_PeekLeftThrow   =6,
    GRENADE_PeekRightThrow  =7,
    GRENADE_MAX             =8,
};

class R6WEAPONS_API AR6GrenadeWeapon : public AR6Gadget
{
public:
    BYTE m_eThrow;
    BITFIELD m_bCanThrowGrenade:1 GCC_PACK(4);
    BITFIELD m_bFistPersonAnimFinish:1;
    BITFIELD m_bPinToRemove:1;
    BITFIELD m_bReadyToThrow:1;
    DECLARE_CLASS(AR6GrenadeWeapon,AR6Gadget,0,R6Weapons)
    NO_DEFAULT_CONSTRUCTOR(AR6GrenadeWeapon)
};


class R6WEAPONS_API AR6HBSGadget : public AR6Gadget
{
public:
    BITFIELD m_bHeartBeatOn:1 GCC_PACK(4);
    class USound* m_sndActivation GCC_PACK(4);
    class USound* m_sndDesactivation;
    DECLARE_FUNCTION(execToggleHeartBeatProperties);
    DECLARE_CLASS(AR6HBSGadget,AR6Gadget,0,R6Weapons)
    NO_DEFAULT_CONSTRUCTOR(AR6HBSGadget)
};

enum eHitResult
{
    HR_NoMaterial           =0,
    HR_Explode              =1,
    HR_Ricochet             =2,
    HR_GoThrough            =3,
    HR_MAX                  =4,
};
enum EHitType
{
    HIT_Impact              =0,
    HIT_Ricochet            =1,
    HIT_Exit                =2,
    HIT_MAX                 =3,
};

class R6WEAPONS_API AR6Bullet : public AR6AbstractBullet
{
public:
    INT m_iEnergy;
    INT m_iPenetrationFactor;
    INT m_iNoArmorModifier;
    INT m_iBulletGroupID;
    BITFIELD m_bBulletIsGone:1 GCC_PACK(4);
    BITFIELD m_bIsGrenade:1;
    BITFIELD m_bBulletDeactivated:1;
    BITFIELD bShowLog:1;
    FLOAT m_fKillStunTransfer GCC_PACK(4);
    FLOAT m_fRangeConversionConst;
    FLOAT m_fRange;
    FLOAT m_fExplosionRadius;
    FLOAT m_fKillBlastRadius;
    FLOAT m_fExplosionDelay;
    class AActor* m_AffectedActor;
    class AR6BulletManager* m_BulletManager;
    FVector m_vSpawnedPosition;
    FStringNoInit m_szAmmoName;
    FStringNoInit m_szAmmoType;
    FStringNoInit m_szBulletType;
    DECLARE_FUNCTION(execBulletGoesThroughSurface);
    DECLARE_CLASS(AR6Bullet,AR6AbstractBullet,0,R6Weapons)
    NO_DEFAULT_CONSTRUCTOR(AR6Bullet)
};

enum eGrenadePawnPose
{
    GPP_Stand               =0,
    GPP_Crouch              =1,
    GPP_ProneFacing         =2,
    GPP_MAX                 =3,
};
enum eGrenadeBoneTarget
{
    GBT_Head                =0,
    GBT_Body                =1,
    GBT_LeftArm             =2,
    GBT_RightArm            =3,
    GBT_LeftLeg             =4,
    GBT_RightLeg            =5,
    GBT_MAX                 =6,
};
enum EGrenadeType
{
    GTYPE_None              =0,
    GTYPE_Smoke             =1,
    GTYPE_TearGas           =2,
    GTYPE_FlashBang         =3,
    GTYPE_BreachingCharge   =4,
    GTYPE_MAX               =5,
};

class R6WEAPONS_API AR6Grenade : public AR6Bullet
{
public:
    BYTE m_eOldPhysic;
    BYTE m_eExplosionSoundType;
    BYTE m_eGrenadeType;
    INT m_iNumberOfFragments;
    BITFIELD m_bFirstImpact:1 GCC_PACK(4);
    BITFIELD m_bDestroyedByImpact:1;
    FLOAT m_fDuration GCC_PACK(4);
    FLOAT m_fShakeRadius;
    FLOAT m_fEffectiveOutsideKillRadius;
    class USound* m_sndExplosionSound;
    class USound* m_sndExplosionSoundStop;
    class USound* m_sndExplodeMetal;
    class USound* m_sndExplodeWater;
    class USound* m_sndExplodeAir;
    class USound* m_sndExplodeDirt;
    class USound* m_ImpactSound;
    class USound* m_ImpactGroundSound;
    class USound* m_ImpactWaterSound;
    class USound* m_sndEarthQuake;
    class AR6DemolitionsGadget* m_Weapon;
    class AEmitter* m_pEmmiter;
    class UClass* m_pExplosionParticles;
    class UClass* m_pExplosionParticlesLOW;
    class UClass* m_pExplosionLight;
    class UClass* m_GrenadeDecalClass;
    FsDamagePercentage m_DmgPercentStand;
    FsDamagePercentage m_DmgPercentCrouch;
    FsDamagePercentage m_DmgPercentProne;
    DECLARE_CLASS(AR6Grenade,AR6Bullet,0,R6Weapons)
    NO_DEFAULT_CONSTRUCTOR(AR6Grenade)
};


class R6WEAPONS_API AR6SmokeCloud : public AActor
{
public:
    FLOAT m_fStartTime;
    FLOAT m_fExpansionTime;
    FLOAT m_fFinalRadius;
    FLOAT m_fCurrentRadius;
    class AR6Grenade* m_grenade;
    DECLARE_CLASS(AR6SmokeCloud,AActor,0,R6Weapons)
    NO_DEFAULT_CONSTRUCTOR(AR6SmokeCloud)
};


class R6WEAPONS_API AR6Reticule : public AActor
{
public:
    INT m_iNonFunctionnalX;
    INT m_iNonFunctionnalY;
    BITFIELD m_bIdentifyCharacter:1 GCC_PACK(4);
    BITFIELD m_bAimingAtFriendly:1;
    BITFIELD m_bShowNames:1;
    FLOAT m_fAccuracy GCC_PACK(4);
    FLOAT m_fZoomScale;
    FLOAT m_fReticuleOffsetX;
    FLOAT m_fReticuleOffsetY;
    class UFont* m_SmallFont_14pt;
    FColor m_color;
    FStringNoInit m_CharacterName;
    DECLARE_CLASS(AR6Reticule,AActor,0|CLASS_Config,R6Weapons)
    NO_DEFAULT_CONSTRUCTOR(AR6Reticule)
};

#endif

AUTOGENERATE_FUNCTION(AR6HBSGadget,2700,execToggleHeartBeatProperties);
AUTOGENERATE_FUNCTION(AR6Bullet,2001,execBulletGoesThroughSurface);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
